# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e8ef47723a3a46224591f7a5f67146349b9f45852835a445a6eac461f75e25af5fa5c368bed6bd94d2ca4141ea0f8254358e5ae2b0eb4084232aaac65655c34

test:
  secret_key_base: f57cdfa6f8485fec4b7d0c508e3fdd9a629425d0a61a850e0d4405306ca56fab8bc5ab21984aaff434f0de14e9a3d1e41356864cd5c6da4f53f8188c6d60540a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
